version: '3.9'

services:
  db:
    image: postgres:16
    container_name: chess_postgres
    restart: always
    environment:
      POSTGRES_USER: edwin
      POSTGRES_PASSWORD: edwin123
      POSTGRES_DB: chess_db
    ports:
      - "5433:5432"
